version: "1.0"
services:
  name: my_database
  composition:
    my-redis-db-host:
      image: redis:latest
      ports:
        - 6379     
steps:
  main_clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "codefreshdemo/demochat"
    revision: "master"
    stage: "clone"
    #my_integration_tests:
    #image: my-app-image
    #title: Running integration tests
    #commands:
      #- npm run test
    #services:
      #- my_database
